################################################################################
#  helm/badchart/templates/deployment.yaml  — renders INSECURE K8S
#  Checkov 'helm' framework renders this then runs CKV_K8S_* checks.
####################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-insecure
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      hostNetwork: true
      hostPID: true
      automountServiceAccountToken: true
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            capabilities:
              add: ["ALL"]
          env:
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.secret.awsKey }}"
          # no resource limits, no probes
      volumes:
        - name: host
          hostPath:
            path: /
