image:
  repository: nginx
  tag: latest          # unpinned
replicaCount: 1
securityContext:
  privileged: true
  runAsNonRoot: false
  runAsUser: 0
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
secret:
  awsKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
